### ISSUE TITLE
java.lang.InterruptedException while using jobcacher plugin

### ISSUE THREAD

**Issue by ramesh-krishnan-metro** [jenkinsci/jobcacher-plugin#75]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

linux - docker

### Reproduction steps

Hi Team,
we are using this cache plugin but getting the below error. please advise here

java.lang.InterruptedException
	at java.base/java.lang.Object.wait(Native Method)
	at hudson.remoting.Request.call(Request.java:177)
	at hudson.remoting.Channel.call(Channel.java:1000)
	at hudson.FilePath.act(FilePath.java:1164)
	at hudson.FilePath.act(FilePath.java:1153)
	at jenkins.plugins.jobcacher.arbitrary.TarGzArbitraryFileCacheStrategy.compress(TarGzArbitraryFileCacheStrategy.java:29)
	at jenkins.plugins.jobcacher.arbitrary.AbstractCompressingArbitraryFileCacheStrategy.cache(AbstractCompressingArbitraryFileCacheStrategy.java:19)
	at jenkins.plugins.jobcacher.ArbitraryFileCache$SaverImpl.save(ArbitraryFileCache.java:272)
	at jenkins.plugins.jobcacher.CacheManager.save(CacheManager.java:99)
	at jenkins.plugins.jobcacher.pipeline.CacheStep$ExecutionCallback.complete(CacheStep.java:167)

### Expected Results

Working as expected

### Actual Results

Working as expected

**Comment by repolevedavaj** [comment]
Is this happening in every execution?

**Comment by repolevedavaj** [comment]
@neilmenon thank you for your contribution. Could you monitor your CPU/RAM usage while it's creating the cache? Maybe it's unresponsive and therefore the connection gets dropped?

**Comment by repolevedavaj** [comment]
OK, I found a similar issue in the Jenkins JIRA: https://issues.jenkins.io/browse/JENKINS-48283

They had a problem with some process which needed more than five minutes, which then got interrupted because of some timeout in the the CPS thread: https://github.com/jenkinsci/workflow-cps-plugin/blob/master/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThread.java#L183

**Comment by neilmenon** [comment]
@repolevedavaj thanks for the response and lightning fast work on this. To answer your question, cache size is big, uncompressed somewhere around 700-800 MB.

Sadly, I am unable to test this change myself with this scenario as I am not the administrator on the Jenkins instance which threw the exception. So I cannot cut to this feature branch easily.

@ramesh-krishnan-metro if possible, can you please help test this from your side?

@repolevedavaj I do have once question, actually, probably unrelated. I tried setting the compression method to `NONE` as part of the testing for this issue and wound up with a security exception:

```
java.lang.SecurityException: Sending hudson.FilePath$Exists from agent to controller is prohibited.
See https://www.jenkins.io/redirect/security-144 for more details
```

I understand the error, but I am wondering, once we get the `InterruptedException` out of the way, will Jenkins be throwing me this security exception? Or is this `hudson.FilePath$Exists` only used in the simple caching method (`NONE`)? Thanks!

**Comment by repolevedavaj** [comment]
@neilmenon regarding your question, this should only happen while using `NONE`. Actually there is another ticket to remove this "compression method" exactly because of this.

**Comment by repolevedavaj** [comment]
@neilmenon I released the change I did as it is an improvement anyway (https://github.com/jenkinsci/jobcacher-plugin/releases/tag/291.v1b_2284da_5dd7). Let me know if it fixes your issue.

**Comment by neilmenon** [comment]
@repolevedavaj Unfortunately, the issue persists with the new release, and I am seeing different line numbers in the stack trace:

```
java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at hudson.remoting.Request.call(Request.java:177)
	at hudson.remoting.Channel.call(Channel.java:999)
	at hudson.FilePath.act(FilePath.java:1194)
	at hudson.FilePath.act(FilePath.java:1183)
	at jenkins.plugins.jobcacher.arbitrary.TarGzArbitraryFileCacheStrategy.compress(TarGzArbitraryFileCacheStrategy.java:29)
	at jenkins.plugins.jobcacher.arbitrary.AbstractCompressingArbitraryFileCacheStrategy.cache(AbstractCompressingArbitraryFileCacheStrategy.java:19)
	at jenkins.plugins.jobcacher.ArbitraryFileCache$SaverImpl.save(ArbitraryFileCache.java:289)
	at jenkins.plugins.jobcacher.CacheManager.save(CacheManager.java:99)
	at jenkins.plugins.jobcacher.pipeline.CacheStep$ExecutionCallback.complete(CacheStep.java:160)
	at jenkins.plugins.jobcacher.pipeline.CacheStep$ExecutionCallback.onSuccess(CacheStep.java:141)
	at org.jenkinsci.plugins.workflow.cps.CpsBodyExecution$SuccessAdapter.receive(CpsBodyExecution.java:372)
	at com.cloudbees.groovy.cps.Outcome.resumeFrom(Outcome.java:73)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:166)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:136)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:275)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:187)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:420)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:95)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:330)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:294)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Finished: FAILURE
```

**Comment by repolevedavaj** [comment]
@neilmenon thanks for the feedback. Can you tell me you current Jenkins version you are using?

**Comment by neilmenon** [comment]
@repolevedavaj `2.346.3`. Thank you!

**Comment by zencode1** [comment]
I have encountered this same issue.  My directory being cached is 1.5GB.  Using the default settings, it takes just under 5 minutes to compress and starts to transfer to the Jenkins server.  At the 5-minute mark, the exception is thrown and the transfer is terminated (around 380MB).

I changed the compression method to `TARGZ_BEST_SPEED` which allows the caching operation to succeed in 3.5 minutes.  The compressed file is 1.1GB in this case.

Jenkins server is 2.387.2 (redhat linux)
Jenkins agent is Windows Server 2019
Job Cacher version: 378.v5e7c64638d63

**Comment by repolevedavaj** [comment]
I will close this ticket for now as i could not reproduce it anymore. Feel free to reopen in case you run into the same issue again.
